import { StyleSheet } from "react-native";
export default StyleSheet.create({
    container:{
        backgroundColor: 'white',
        width:'100%',
        height:'100%',
        alignItems:'center',
    },
    viewTitle:{
        width:'80%',
        padding:5,
        alignItems:'center',
        borderRadius:20,
        height:'5%',
        margin:10,
        backgroundColor: "#dc261e",
    },
    tituloMaquinas:{
        fontSize:20,
        textAlign:'center',
        fontWeight:'bold',
        color:'white',
    },
    imgMaquina:{
        width:'60%',
        height:'20%',
        borderColor:'black',
        borderWidth:5,
        borderRadius:20,
        resizeMode:'contain',
    },
    viewHorario:{
        width:'80%',
        height:'70%',
        alignItems:'center',
    },
    botoes:{
        backgroundColor:'white',
        borderRadius:10,
        borderWidth:1,
        margin:5
    },
    pressionado:{
        borderColor:'yellow'
    },
    textBotao:{
        fontSize:20,
    },
    scroll:{
        width:'80%',
        height:'70%',
        margin:10,
        borderRadius:10,
        borderWidth:5,
        borderColor:'black',
    },
    confirmButton:{
        backgroundColor:'#dc261e',
        margin:15,
        borderRadius:5,
        alignItems:'center',
        alignContent:'center',
        width:200,
        height:70,
    },
    confirmTxt:{
        fontSize:18,
        color:'white'
    },
    modal:{
        width:'80%',
        height:'80%',
        backgroundColor:'blue'
    }
})